export const get_storageListForSelect_success = 'get_storageListForSelect_success'
export const get_storageListForSelect_failed = 'get_storageListForSelect_failed'
export const get_storageListForSelect_error = 'get_storageListForSelect_error'
export const get_storageListForSelect_waiting = 'get_storageListForSelect_waiting'