export const GET_CARINFO_SUCCESS = 'GET_CARINFO_SUCCESS'
export const GET_CARINFO_FAILED = 'GET_CARINFO_FAILED'
export const GET_CARINFO_WAITING = 'GET_CARINFO_WAITING'
export const GET_CARINFO_ERROR = 'GET_CARINFO_ERROR'
export const RESET_GET_CARINFO = 'RESET_GET_CARINFO'

export const EXPORT_CAR_SUCCESS = 'EXPORT_CAR_SUCCESS'
export const EXPORT_CAR_FAILED = 'EXPORT_CAR_FAILED'
export const EXPORT_CAR_WAITING = 'EXPORT_CAR_WAITING'
export const EXPORT_CAR_ERROR = 'EXPORT_CAR_ERROR'
export const RESET_EXPORT_CAR = 'RESET_EXPORT_CAR'

export const APPEND_CAR_IMAGE_SUCCESS = 'APPEND_CAR_IMAGE_SUCCESS'
export const APPEND_CAR_IMAGE_FAILED = 'APPEND_CAR_IMAGE_FAILED'
export const APPEND_CAR_IMAGE_WAITING = 'APPEND_CAR_IMAGE_WAITING'
export const APPEND_CAR_IMAGE_ERROR = 'APPEND_CAR_IMAGE_ERROR'
export const RESET_APPEND_CAR_IMAGE = 'RESET_APPEND_CAR_IMAGE'

export const MOVE_CAR_SUCCESS = 'MOVE_CAR_SUCCESS'
export const MOVE_CAR_FAILED = 'MOVE_CAR_FAILED'
export const MOVE_CAR_WAITING = 'MOVE_CAR_WAITING'
export const MOVE_CAR_ERROR = 'MOVE_CAR_ERROR'
export const RESET_MOVE_CAR = 'RESET_MOVE_CAR'

export const CHANGE_VIEWTYPE = 'CHANGE_VIEWTYPE'

export const UPDATE_CARINFO_SUCCESS = 'UPDATE_CARINFO_SUCCESS'
export const UPDATE_CARINFO_ERROR = 'UPDATE_CARINFO_ERROR'
export const UPDATE_CARINFO_WAITING = 'UPDATE_CARINFO_WAITING'
export const UPDATE_CARINFO_FAILED = 'UPDATE_CARINFO_FAILED'


export const CHANGE_EDITCARINFRO_MODEL = 'CHANGE_EDITCARINFRO_MODEL'
export const CHANGE_EDITCARINFRO_COLOR = 'CHANGE_EDITCARINFRO_COLOR'
export const CHANGE_EDITCARINFRO_REMARK = 'CHANGE_EDITCARINFRO_REMARK'
export const CHANGE_EDITCARINFRO_PRODATE = 'CHANGE_EDITCARINFRO_PRODATE'
export const CHANGE_EDITCARINFRO_PLANOUTIME = 'CHANGE_EDITCARINFRO_PLANOUTIME'
export const CHANGE_EDITCARINFRO_ENGINENUM = 'CHANGE_EDITCARINFRO_ENGINENUM'
export const CHANGE_EDITCARINFO_FIELD = 'CHANGE_EDITCARINFO_FIELD'
export const CHANGE_IMPORTAGAIN_PLANOUTIME = 'CHANGE_IMPORTAGAIN_PLANOUTIME'
export const CHANGE_IMPORTAGAIN_PARKING = 'CHANGE_IMPORTAGAIN_PARKING'


export const UPDATE_CARINFO_PLANOUTTIME_SUCCESS = 'UPDATE_CARINFO_PLANOUTTIME_SUCCESS'
export const UPDATE_CARINFO_PLANOUTTIME_ERROR = 'UPDATE_CARINFO_PLANOUTTIME_ERROR'
export const UPDATE_CARINFO_PLANOUTTIME_WAITING = 'UPDATE_CARINFO_PLANOUTTIME_WAITING'
export const UPDATE_CARINFO_PLANOUTTIME_FAILED = 'UPDATE_CARINFO_PLANOUTTIME_FAILED'



export const IMPORT_AGAIN_SUCCESS = 'IMPORT_AGAIN_SUCCESS'
export const IMPORT_AGAIN_FAILED = 'IMPORT_AGAIN_FAILED'
export const IMPORT_AGAIN_ERROR = 'IMPORT_AGAIN_ERROR'
export const IMPORT_AGAIN_WAITING = 'IMPORT_AGAIN_WAITING'
export const RESET_IMPORT_AGAIN = 'RESET_IMPORT_AGAIN'

