export const GET_CARINFO_SUCCESS = 'GET_CARINFO_SUCCESS'
export const GET_CARINFO_FAILED = 'GET_CARINFO_SUCCESS'
export const GET_CARINFO_WAITING = 'GET_CARINFO_SUCCESS'


export const EXPORT_CAR_SUCCESS = 'EXPORT_CAR_SUCCESS'
export const EXPORT_CAR_FAILED = 'EXPORT_CAR_FAILED'
export const EXPORT_CAR_WAITING = 'EXPORT_CAR_WAITING'

export const APPEND_CAR_IMAGE_SUCCESS = 'APPEND_CAR_IMAGE_SUCCESS'
export const APPEND_CAR_IMAGE_FAILED = 'APPEND_CAR_IMAGE_FAILED'
export const APPEND_CAR_IMAGE_WAITING = 'APPEND_CAR_IMAGE_WAITING'

export const MOVE_CAR_SUCCESS = 'MOVE_CAR_SUCCESS'
export const MOVE_CAR_FAILED = 'MOVE_CAR_FAILED'
export const MOVE_CAR_WAITING = 'MOVE_CAR_WAITING'