export const GET_CARLIST_SUCCESS = 'GET_CARLIST_SUCCESS'
export const GET_CARLIST_FAILED = 'GET_CARLIST_FAILED'
export const GET_CARLIST_WAITING = 'GET_CARLIST_WAITING'
export const GET_CARLIST_ERROR = 'GET_CARLIST_ERROR'

export const GET_CARLIST_MORE_SUCCESS = 'GET_CARLIST_MORE_SUCCESS'
export const GET_CARLIST_MORE_FAILED = 'GET_CARLIST_MORE_FAILED'
export const GET_CARLIST_MORE_WAITING = 'GET_CARLIST_MORE_WAITING'
export const GET_CARLIST_MORE_ERROR = 'GET_CARLIST_MORE_ERROR'


export const REMOVE_CAR = 'REMOVE_CAR'