export const GET_CARMAKES_SUCCESS = 'GET_CARMAKES_SUCCESS'
export const GET_CARMAKES_FAILED = 'GET_CARMAKES_FAILED'
export const GET_CARMAKES_WAITING = 'GET_CARMAKES_WAITING'
export const GET_CARMAKES_ERROR = 'GET_CARMAKES_ERROR'

