export const GET_CARMODELS_SUCCESS = 'GET_CARMODELS_SUCCESS'
export const GET_CARMODELS_FAILED = 'GET_CARMODELS_FAILED'
export const GET_CARMODELS_WAITING = 'GET_CARMODELS_WAITING'
export const GET_CARMODELS_ERROR = 'GET_CARMODELS_ERROR'


