export const GET_STORAGES_HOME_SUCCESS = 'GET_STORAGES_HOME_SUCCESS'
export const GET_STORAGES_HOME_FAILED = 'GET_STORAGES_HOME_FAILED'
export const GET_STORAGES_HOME_WAITING = 'GET_STORAGES_HOME_WAITING'
export const GET_STORAGES_HOME_ERROR = 'GET_STORAGES_HOME_ERROR'


export const GET_RECORDS_HOME_SUCCESS = 'GET_RECORDS_HOME_SUCCESS'
export const GET_RECORDS_HOME_FAILED = 'GET_RECORDS_HOME_FAILED'
export const GET_RECORDS_HOME_WAITING = 'GET_RECORDS_HOME_WAITING'
export const GET_RECORDS_HOME_ERROR = 'GET_RECORDS_HOME_ERROR'
export const RESET_GET_RECORDS_HOME = 'RESET_GET_RECORDS_HOME'
export const RESET_GET_STORAGES_HOME = 'RESET_GET_STORAGES_HOME'