export const IMPORT_CAR_SUCCESS = 'IMPORT_CAR_SUCCESS'
export const IMPORT_CAR_ERROR = 'IMPORT_CAR_ERROR'
export const IMPORT_CAR_FAILED = 'IMPORT_CAR_FAILED'
export const IMPORT_CAR_WAITING = 'IMPORT_CAR_WAITING'

export const IMPORT_CAR_RESET_EXECUTE_STATUS = 'IMPORT_CAR_RESET_EXECUTE_STATUS'
export const IMPORT_CAR_RESET = 'IMPORT_CAR_RESET'

export const CHANGE_IMPORTCAR_FIELD = 'CHANGE_IMPORTCAR_FIELD'




