export const IMPORT_CAR_IMAGE_SUCCESS = 'IMPORT_CAR_IMAGE_SUCCESS'
export const IMPORT_CAR_IMAGE_FAILED = 'IMPORT_CAR_IMAGE_FAILED'
export const IMPORT_CAR_IMAGE_WAITING = 'IMPORT_CAR_IMAGE_WAITING'
export const IMPORT_CAR_IMAGE_ERROR = 'IMPORT_CAR_IMAGE_ERROR'
export const RESET_IMPORT_CAR_IMAGE = 'RESET_IMPORT_CAR_IMAGE'


export const DELETE_IMPORTCARIMAGE_SUCCESS = 'DELETE_IMPORTCARIMAGE_SUCCESS'
export const DELETE_IMPORTCARIMAGE_ERROR = 'DELETE_IMPORTCARIMAGE_ERROR'
export const DELETE_IMPORTCARIMAGE_FAILED = 'DELETE_IMPORTCARIMAGE_FAILED'
export const DELETE_IMPORTCARIMAGE_WAITING = 'DELETE_IMPORTCARIMAGE_WAITING'
export const RESET_IMPORTCARIMAGE = 'RESET_IMPORTCARIMAGE'
