export const GET_PARKINGLIST_FAILED = 'GET_PARKINGLIST_FAILED'
export const GET_PARKINGLIST_SUCCESS = 'GET_PARKINGLIST_SUCCESS'
export const GET_PARKINGLIST_WAITING = 'GET_PARKINGLIST_WAITING'
export const GET_PARKINGLIST_ERROR = 'GET_PARKINGLIST_ERROR'