export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED'
export const CHANGE_PASSWORD_WAITING = 'CHANGE_PASSWORD_WAITING'
export const RESET_CHANGE_PASSWORD = 'RESET_CHANGE_PASSWORD'
