export const GET_RECORD_LIST_VIEW_FAILED = 'GET_RECORD_LIST_VIEW_FAILED'
export const GET_RECORD_LIST_VIEW_SUCCESS = 'GET_RECORD_LIST_VIEW_SUCCESS'
export const GET_RECORD_LIST_VIEW_WAITING = 'GET_RECORD_LIST_VIEW_WAITING'
export const GET_RECORD_LIST_VIEW_ERROR = 'GET_RECORD_LIST_VIEW_ERROR'
export const CHANGE_RECORD_LIST_TAB = 'CHANGE_RECORD_LIST_TAB'


export const RESET_RECORD_LIST_VIEW = 'RESET_RECORD_LIST_VIEW'
export const GET_RECORDLIST_MORE_SUCCESS = 'GET_RECORDLIST_MORE_SUCCESS'
export const GET_RECORDLIST_MORE_FAILED = 'GET_RECORDLIST_MORE_FAILED'
export const GET_RECORDLIST_MORE_WAITING = 'GET_RECORDLIST_MORE_WAITING'
export const GET_RECORDLIST_MORE_ERROR = 'GET_RECORDLIST_MORE_ERROR'
