export const SEARCH_CARLIST_SUCCESS = 'SEARCH_CARLIST_SUCCESS'
export const SEARCH_CARLIST_FAILED = 'SEARCH_CARLIST_FAILED'
export const SEARCH_CARLIST_WAITING = 'SEARCH_CARLIST_WAITING'
export const SEARCH_CARLIST_ERROR = 'SEARCH_CARLIST_ERROR'
export const RESET_SEARCH_CARLIST = 'RESET_SEARCH_CARLIST'

export const SEARCH_CARLIST_MORE_SUCCESS = 'SEARCH_CARLIST_MORE_SUCCESS'
export const SEARCH_CARLIST_MORE_FAILED = 'SEARCH_CARLIST_MORE_FAILED'
export const SEARCH_CARLIST_MORE_WAITING = 'SEARCH_CARLIST_MORE_WAITING'
export const SEARCH_CARLIST_MORE_ERROR = 'SEARCH_CARLIST_MORE_ERROR'

export const REMOVE_SEARCH_CAR = 'REMOVE_SEARCH_CAR'
export const CHANGE_SEARCHVIN = 'CHANGE_SEARCHVIN'