export const GET_SELECTSTORAGELIST_SUCCESS = 'GET_SELECTSTORAGELIST_SUCCESS'
export const GET_SELECTSTORAGELIST_WAITING = 'GET_SELECTSTORAGELIST_WAITING'
export const GET_SELECTSTORAGELIST_FAILED = 'GET_SELECTSTORAGELIST_FAILED'
export const GET_SELECTSTORAGELIST_ERROR = 'GET_SELECTSTORAGELIST_ERROR'   