export const GET_STORAGEPARKINGS_SUCCESS = 'GET_STORAGEPARKINGS_SUCCESS'
export const GET_STORAGEPARKINGS_WAITING = 'GET_STORAGEPARKINGS_WAITING'
export const GET_STORAGEPARKINGS_FAILED = 'GET_STORAGEPARKINGS_FAILED'
export const GET_STORAGEPARKINGS_ERROR = 'GET_STORAGEPARKINGS_ERROR'