export const GET_STORAGELIST_SUCCESS = 'GET_STORAGELIST_SUCCESS'
export const GET_STORAGELIST_WAITING = 'GET_STORAGELIST_WAITING'
export const GET_STORAGELIST_FAILED = 'GET_STORAGELIST_FAILED'
export const GET_STORAGELIST_ERROR = 'GET_STORAGELIST_ERROR'