export const GET_VERSION_SUCCESS = 'GET_VERSION_SUCCESS'
export const GET_VERSION_WAITING = 'GET_VERSION_WAITING'
export const GET_VERSION_FAILED = 'GET_VERSION_FAILED'
export const GET_VERSION_ERROR = 'GET_VERSION_ERROR'

export const VALIDATE_TOKEN_SUCCESS = 'VALIDATE_TOKEN_SUCCESS'
export const VALIDATE_TOKEN_FAILED = 'VALIDATE_TOKEN_FAILED'
export const VALIDATE_TOKEN_ERROR = 'VALIDATE_TOKEN_ERROR'
export const VALIDATE_TOKEN_WAITING = 'VALIDATE_TOKEN_WAITING'