export const GET_VERSION_SUCCESS = 'GET_VERSION_SUCCESS'
export const GET_VERSION_LOADING = 'GET_VERSION_LOADING'
export const GET_VERSION_FAILED = 'GET_VERSION_FAILED'

export const VALIDATE_TOKEN_SUCCESS = 'VALIDATE_TOKEN_SUCCESS'
export const VALIDATE_TOKEN_FAILED = 'VALIDATE_TOKEN_FAILED'
export const VALIDATE_TOKEN_LOADING= 'VALIDATE_TOKEN_LOADING'