export const update_carImage_success = 'update_carImage_success'
export const update_carImage_failed = 'update_carImage_failed'
export const update_carImage_error = 'update_carImage_error'
export const update_carImage_waiting = 'update_carImage_waiting'
export const update_carImage_partSuccess = 'update_carImage_partSuccess'

export const update_transImage_success = 'update_transImage_success'
export const update_transImage_failed = 'update_transImage_failed'
export const update_transImage_error = 'update_transImage_error'
export const update_transImage_waiting = 'update_transImage_waiting'
export const update_transImage_partSuccess = 'update_transImage_partSuccess'

export const update_storageImage_success = 'update_storageImage_success'
export const update_storageImage_failed = 'update_storageImage_failed'
export const update_storageImage_error = 'update_storageImage_error'
export const update_storageImage_waiting = 'update_storageImage_waiting'
export const update_storageImage_partSuccess = 'update_storageImage_partSuccess'

export const get_imageListForCarInfo_success = 'get_imageListForCarInfo_success'
export const get_imageListForCarInfo_failed = 'get_imageListForCarInfo_failed'
export const get_imageListForCarInfo_error = 'get_imageListForCarInfo_error'
export const get_imageListForCarInfo_waiting = 'get_imageListForCarInfo_waiting'

export const upload_videoForCarInfo_success = 'upload_videoForCarInfo_success'
export const upload_videoForCarInfo_failed = 'upload_videoForCarInfo_failed'
export const upload_videoForCarInfo_error = 'upload_videoForCarInfo_error'
export const upload_videoForCarInfo_waiting = 'upload_videoForCarInfo_waiting'

export const set_indexForCarInfoImage = 'set_indexForCarInfoImage'
export const set_carImageIndexForCarInfoImage = 'set_carImageIndexForCarInfoImage'
export const set_transImageIndexForCarInfoImage = 'set_transImageIndexForCarInfoImage'
export const set_storageImageIndexForCarInfoImage = 'set_storageImageIndexForCarInfoImage'