export const GET_CAR_LIST_SUCCESS='GET_CAR_LIST_SUCCESS'
export const GET_CAR_LIST_FAILED='GET_CAR_LIST_FAILED'
export const GET_CAR_LIST_START='GET_CAR_LIST_START'
export const GET_CAR_BY_ID='GET_CAR_BY_ID'
