export const FIRST_GET_CAR_LIST_SUCCESS = 'FIRST_GET_CAR_LIST_SUCCESS'
export const GET_CAR_LIST_SUCCESS = 'GET_CAR_LIST_SUCCESS'
export const GET_CAR_LIST_FAILED = 'GET_CAR_LIST_FAILED'
export const GET_CAR_LIST_START = 'GET_CAR_LIST_START'

export const EXPORT_CAR_SUCCESS = 'EXPORT_CAR_SUCCESS'
export const EXPORT_CAR_FAILED = 'EXPORT_CAR_FAILED'
export const EXPORT_CAR_START = 'EXPORT_CAR_START'

