export const FIRST_GET_RECORD_LIST_SUCCESS = 'FIRST_GET_RECORD_LIST_SUCCESS'
export const GET_RECORD_LIST_FAILED = 'GET_RECORD_LIST_FAILED'
export const GET_RECORD_LIST_SUCCESS = 'GET_RECORD_LIST_SUCCESS'

export const GET_RECORD_LIST_LOADING = 'GET_RECORD_LIST_LOADING'
