export const FIRST_GET_RECORD_LIST_SUCCESS = 'FIRST_GET_RECORD_LIST_SUCCESS'
export const GET_RECORD_LIST_FAILED = 'GET_RECORD_LIST_FAILED'
export const GET_RECORD_LIST_START = 'GET_RECORD_LIST_START'
export const GET_RECORD_LIST_SUCCESS = 'GET_RECORD_LIST_SUCCESS'

 //export const FIRST_RECORD_LIST_SUCCESS = 'FIRST_RECORD_LIST_SUCCESS'

// export const GET_RECORD_BYCARID_SUCCESS = 'GET_RECORD_BYCARID_SUCCESS'
// export const GET_RECORD_BYCARID_FAILED = 'GET_RECORD_BYCARID_FAILED'
// export const GET_RECORD_BYCARID_START = 'GET_RECORD_BYCARID_START'