/**
 * Created by lingxue on 2017/4/17.
 */

export const GET_STORAGE_DATE_LIST_SUCCESS = 'GET_STORAGE_DATE_LIST_SUCCESS'
// export const GET_PARKING_BY_ID = 'GET_PARKING_BY_ID'
export const GET_STORAGE_DATE_LIST_LOADING = 'GET_STORAGE_DATE_LIST_LOADING'
export const GET_STORAGE_DATE_LIST_FAILED = 'GET_STORAGE_DATE_LIST_FAILED'
